default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: adavancedfeature_development
test:
  <<: *default
  database: adavancedfeature_test

production:
  <<: *default
  database: adavancedfeature_production
  username: sample
  password: <%= ENV['SAMPLE_DATABASE_PASSWORD'] %>
